version: '3.3'
services:
  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    ports:
       - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: dtpopsnake
    restart: always
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
       - db
    restart: always
    ports:
      - '8080:80'